### PR TITLE
V2 bringup

### PR DESCRIPTION
**Pull request by theRookieCoder**
A PR extension (?) of https://github.com/theRookieCoder/ferinth/pull/3

### CODE REVIEW

**Comment by theRookieCoder** [comment]
I think we can rework [this commit](https://github.com/4JX/ferinth/commit/69d23d00d1a485631e26b1e56998c217831a6e2b) after transitioning to `url` (I'm doing that right now)

**Comment by theRookieCoder** [comment]
I just realised the doctests are completely broken they just pass all the time

Edit: It seems that errors that occur in `tokio_test::block_on()` aren't caught at all they're just ignored! This is because the result of the async block is ignored 🤦🏻‍♂️. But it seems panics in the async block do cause tokio-test to panic

Edit: I'm just doing this now
```rust
/// # #[tokio::main]
/// # async fn main() -> Result<(), ferinth::Error> {
/// ...actual test...
/// # Ok(()) }
```
Not checking `Result`s is quite an oversight for a testing library imo

**Comment by 4JX** [comment]
> I think we can rework [this commit](https://github.com/4JX/ferinth/commit/69d23d00d1a485631e26b1e56998c217831a6e2b) after transitioning to `url` (I'm doing that right now)

Good idea. On that note I'd prefer for the "modloader" enum be placed somewhere more global. I did consider also using it for the `loaders` section of the `Version` struct, but since no guarantees seem to be given for what might appear there I decided against it.

**Comment by theRookieCoder** [comment]
I think the intended way to specify/read mod loaders is to get them from the mod loaders tag

**Comment by theRookieCoder** [comment]
I've done pretty much everything needed to release v2. Any suggestions @4JX?

**Comment by 4JX** [comment]
> I've done pretty much everything needed to release v2. Any suggestions @4JX?

Would still fancy filtering for `list_versions` to be a part of the release, maybe with just a `Vec<String>` for the `loaders` part rather than an enum?

It seems more convenient than doing the same thing with code on the program later on given the API provides support for it.

**Comment by theRookieCoder** [comment]
Ah I see I thought we'd make a seperate pr for that and mod searching. Would releasing that in v2.1 be okay, or you seriously need that feature now?

**Comment by 4JX** [comment]
> Ah I see I thought we'd make a seperate pr for that and mod searching. Would releasing that in v2.1 be okay, or you seriously need that feature now?

Actually yes sounds good 👍. Go for it.

**Comment by theRookieCoder** [comment]
I'll migrate ferium to this to test for any edge cases first. Is a changelog necessary? I mean it's a major release so obviously everything has changed

**Comment by 4JX** [comment]
> I'll migrate ferium to this to test for any edge cases first. Is a changelog necessary? I mean it's a major release so obviously everything has changed

Other than "you should probably substitute mod with project in your function calls" you can probably do a mobile dev changelog and throw everything else under "various improvements"

**Comment by theRookieCoder** [comment]
> you can probably do a mobile dev changelog and throw everything else under "various improvements"

Haha I was thinking of just doing "Initial release" and maybe linking this PR as a 'changelog'

**Comment by theRookieCoder** [comment]
Ferium works fine! Just had to change `get_mod` to `get_project` and edit a few lines to adapt to the new struct defs

**Pull request merged**
